---
kind: pipeline
type: docker
name: default

steps:
 - name: binary build
   image: golang
   environment:
     CGO_ENABLED: 0
   commands:
    - go vet
    - go build

 - name: docker
   image: plugins/docker
   settings:
     registry: git.burble.dn42
     repo: git.burble.dn42/burble.dn42/dn42regsrv
     tags: latest
     username: burble
     password:
       from_secret: TOKEN
     storage_driver: vfs

---
kind: secret
name: TOKEN
get:
  path: burble.dn42/apps/data/drone/secrets/git.burble.dn42
  name: artifact-token
